server:
  port: 8761  #eureka默认端口

eureka:
  instance:
    hostname: ttt
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/